// Generated by CoffeeScript 1.8.0
var __hasProp = {}.hasOwnProperty,
  __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

window.Hand = (function(_super) {
  __extends(Hand, _super);

  function Hand() {
    return Hand.__super__.constructor.apply(this, arguments);
  }

  Hand.prototype.model = Card;

  Hand.prototype.initialize = function(array, deck, isDealer) {
    this.deck = deck;
    this.isDealer = isDealer;
    return this.on('hit', this.checkIfBust);
  };

  Hand.prototype.stand = function() {
    return this.trigger('stand');
  };

  Hand.prototype.hit = function() {
    this.add(this.deck.pop()).last();
    return this.trigger('hit');
  };

  Hand.prototype.scores = function() {
    var hasAce, score;
    hasAce = this.reduce(function(memo, card) {
      return memo || card.get('value') === 1;
    }, false);
    score = this.reduce(function(score, card) {
      return score + (card.get('revealed') ? card.get('value') : 0);
    }, 0);
    if (hasAce) {
      return [score, score + 10];
    } else {
      return [score];
    }
  };

  Hand.prototype.checkIfBust = function() {
    if (this.scores()[0] > 21) {
      if (!this.scores()[1] || this.scores()[1] > 21) {
        return this.trigger('bust');
      }
    }
  };

  Hand.prototype.hasCovered = function() {
    return !this.at(0).get('revealed');
  };

  Hand.prototype.trueScore = function() {
    if (this.scores()[1] < 22) {
      return this.scores()[1];
    } else {
      return this.scores()[0];
    }
  };

  return Hand;

})(Backbone.Collection);
